/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.ControllerInterface;
import java.io.IOException;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import model.Exception.ContainedItemException;
import model.Exception.ItemAmountOutOfBoundsException;
import model.ProductsModelInterface;
import model.ProductsObserver;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author os
 */
public class ChooseProductDialog extends javax.swing.JDialog implements ProductsObserver{
    
    ControllerInterface controller;
    ProductsModelInterface productsModel;

    /**
     * Creates new form ChooseProductDialog
     * @param parent
     * @param modal
     * @param controller
     * @param productsModel
     */
    public ChooseProductDialog(java.awt.Frame parent, boolean modal, ControllerInterface controller, ProductsModelInterface productsModel) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
        productTable.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        this.setTitle("Chọn mặt hàng");
        
        this.controller = controller;
        this.productsModel = productsModel;
        updateProducts();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        productTable = new javax.swing.JTable();
        chooseProductButton = new javax.swing.JButton();
        amountSpinner = new javax.swing.JSpinner();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        productTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã hàng", "Tên mặt hàng", "Nhóm hàng", "Giá bán"
            }
        ));
        jScrollPane1.setViewportView(productTable);

        chooseProductButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        chooseProductButton.setForeground(new java.awt.Color(255, 102, 0));
        chooseProductButton.setText("OK");
        chooseProductButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chooseProductButtonActionPerformed(evt);
            }
        });

        amountSpinner.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 102, 0));
        jLabel1.setText("Số lượng:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 517, Short.MAX_VALUE)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(amountSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17))
            .addGroup(layout.createSequentialGroup()
                .addGap(253, 253, 253)
                .addComponent(chooseProductButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(160, 160, 160)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(amountSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addComponent(chooseProductButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void chooseProductButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chooseProductButtonActionPerformed
        // TODO add your handling code here:
        controller.getChooseProductIndex(productTable.getSelectedRow());
        controller.addPurchase(controller.getCustomerSelected(), controller.getProductSelected(), (Integer) amountSpinner.getValue());
        JOptionPane.showMessageDialog(this, "Thêm thành công");

    }//GEN-LAST:event_chooseProductButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSpinner amountSpinner;
    private javax.swing.JButton chooseProductButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable productTable;
    // End of variables declaration//GEN-END:variables

    @Override
    public void updateProducts() {
        productTable.setModel(DbUtils.resultSetToTableModel(productsModel.getResultSet()));
    }
}
