/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.ControllerInterface;
import javax.swing.ListSelectionModel;
import model.PurchasesModelInterface;
import model.PurchasesObserver;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author os
 */
public class ChooseInvoiceDialog extends javax.swing.JDialog implements PurchasesObserver {
    
    ControllerInterface controller;
    PurchasesModelInterface purchasesModel;

    /**
     * Creates new form ChooseInvoiceDialog
     * @param parent
     * @param modal
     * @param controller
     * @param purchasesModel
     */
    public ChooseInvoiceDialog(java.awt.Frame parent, boolean modal, ControllerInterface controller,
    PurchasesModelInterface purchasesModel) {
        super(parent, modal);
        initComponents();
        
        this.setLocationRelativeTo(null);
        customerTable.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        this.setTitle("Chọn khách hàng");
        
        this.controller = controller;
        this.purchasesModel = purchasesModel;
        
        purchasesModel.registerObserver(this);
        updatePurchases();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        customerTable = new javax.swing.JTable();
        chooseCustomerButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        customerTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã khách hàng", "Họ và tên", "Địa chỉ", "SĐT"
            }
        ));
        jScrollPane1.setViewportView(customerTable);

        chooseCustomerButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        chooseCustomerButton.setForeground(new java.awt.Color(255, 102, 0));
        chooseCustomerButton.setText("OK");
        chooseCustomerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chooseCustomerButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 476, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(200, 200, 200)
                .addComponent(chooseCustomerButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addComponent(chooseCustomerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void chooseCustomerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chooseCustomerButtonActionPerformed
        // TODO add your handling code here:
        controller.updateInvoice(customerTable.getSelectedRow());
        this.dispose();
    }//GEN-LAST:event_chooseCustomerButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton chooseCustomerButton;
    private javax.swing.JTable customerTable;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables


    @Override
    public void updatePurchases() {
        customerTable.setModel(DbUtils.resultSetToTableModel(purchasesModel.getCustomerBought()));
    }

}
